function InsertDateTime()
    local date_time = "### " .. os.date("%Y-%m-%d %H:%M:%S") .. "\n\n"
    vim.api.nvim_buf_set_lines(0, -1, -1, false, vim.split(date_time, "\n"))
end

vim.api.nvim_set_keymap('n', '<leader>dt', ':lua InsertDateTime()<CR>', { noremap = true, silent = true })
vim.keymap.set('n', '<leader>vs', ':vs<CR>', { desc = 'Open vertical split' })
vim.keymap.set('n', '<leader>hs', ':sp<CR>', { desc = 'Open horizontal split' })
vim.keymap.set('n', '<leader>s', ':w<CR>', { desc = 'Write file' })
vim.keymap.set('n', '<leader>qw', ':wq<CR>', { desc = 'Write and Quit' })
vim.keymap.set('n', '<leader>qq', ':q<CR>', { desc = 'Quit' })
vim.keymap.set('n', '<leader>qa', ':qa<CR>', { desc = 'Quit all' })
vim.keymap.set('n', '<C-l>', ':bn<CR>', { desc = 'Forward in tabs' })
vim.keymap.set('n', '<C-h>', ':bn<CR>', { desc = 'Backward in tabs' })
vim.keymap.set('i', '<F12>', '<insert>', { desc = 'insert to replace' })
vim.keymap.set('i', '<Tab>', '<C-p>', { desc = 'Complete word' })
vim.keymap.set('i', "<S-Tab>", "<C-x><C-l>", { desc = "Complete line" })
vim.keymap.set('n', '<leader>x', ':bp<cr>:bd #<cr>', { desc = 'Quit a tab' })
vim.keymap.set('n', '<leader><left>', '<C-w>h', { desc = 'Move to the window to the left' })
vim.keymap.set('n', '<leader><right>', '<C-w>l', { desc = 'Move to the window to the right' })
vim.keymap.set('n', '<leader><up>', '<C-w>k', { desc = 'Move to the window above' })
vim.keymap.set('n', '<leader><down>', '<C-w>j', { desc = 'Move to the window below' })
vim.keymap.set('n', 'z', '*', { desc = 'Find word below cursor' })
vim.keymap.set('n', '<CR>', ':nohlsearch<CR>', { desc = 'Find word below cursor' })
vim.keymap.set('n', "+", "<C-a>", { desc = "Increment numbers" })
vim.keymap.set('n', "-", "<C-x>", { desc = "Decrement numbers" })
vim.keymap.set('n', "<leader>n", ":set relativenumber!<CR>", { desc = "Set Relative Number" })
